services:
  - type: web
    name: jobs-platform-api
    runtime: php
    plan: free
    region: oregon
    buildCommand: |
      composer install
      php artisan config:clear
      php artisan migrate --seed
      php artisan route:cache
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: jobs-platform-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: jobs-platform-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: jobs-platform-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: jobs-platform-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: jobs-platform-db
          property: password

databases:
  - name: jobs-platform-db
    plan: free
    region: oregon
