services:
  - type: web
    name: jobs-platform-api
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: jobs-platform-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: jobs-platform-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: jobs-platform-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: jobs-platform-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: jobs-platform-db
          property: password

databases:
  - name: jobs-platform-db
    plan: free
    region: oregon
